<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241120095738 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE detail_commande (id INT AUTO_INCREMENT NOT NULL, commande_id INT NOT NULL, id_produit_id INT NOT NULL, id_commande_id INT NOT NULL, quantite NUMERIC(15, 2) NOT NULL, prix_de_vente NUMERIC(19, 4) NOT NULL, INDEX IDX_98344FA682EA2E54 (commande_id), INDEX IDX_98344FA6AABEFE2C (id_produit_id), INDEX IDX_98344FA69AF8E3A3 (id_commande_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE detail_livraison (id INT AUTO_INCREMENT NOT NULL, id_livraison_id INT NOT NULL, id_produit_id INT NOT NULL, quantite NUMERIC(15, 2) NOT NULL, INDEX IDX_B7FB4AAAAD958E57 (id_livraison_id), INDEX IDX_B7FB4AAAAABEFE2C (id_produit_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE detail_commande ADD CONSTRAINT FK_98344FA682EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id)');
        $this->addSql('ALTER TABLE detail_commande ADD CONSTRAINT FK_98344FA6AABEFE2C FOREIGN KEY (id_produit_id) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE detail_commande ADD CONSTRAINT FK_98344FA69AF8E3A3 FOREIGN KEY (id_commande_id) REFERENCES commande (id)');
        $this->addSql('ALTER TABLE detail_livraison ADD CONSTRAINT FK_B7FB4AAAAD958E57 FOREIGN KEY (id_livraison_id) REFERENCES livraison (id)');
        $this->addSql('ALTER TABLE detail_livraison ADD CONSTRAINT FK_B7FB4AAAAABEFE2C FOREIGN KEY (id_produit_id) REFERENCES produit (id)');
        $this->addSql('ALTER TABLE appartient DROP FOREIGN KEY appartient_ibfk_1');
        $this->addSql('ALTER TABLE appartient DROP FOREIGN KEY appartient_ibfk_2');
        $this->addSql('ALTER TABLE definie DROP FOREIGN KEY definie_ibfk_2');
        $this->addSql('ALTER TABLE definie DROP FOREIGN KEY definie_ibfk_1');
        $this->addSql('ALTER TABLE communique DROP FOREIGN KEY communique_ibfk_1');
        $this->addSql('ALTER TABLE communique DROP FOREIGN KEY communique_ibfk_2');
        $this->addSql('ALTER TABLE possede DROP FOREIGN KEY possede_ibfk_2');
        $this->addSql('ALTER TABLE possede DROP FOREIGN KEY possede_ibfk_1');
        $this->addSql('ALTER TABLE observe DROP FOREIGN KEY observe_ibfk_1');
        $this->addSql('ALTER TABLE observe DROP FOREIGN KEY observe_ibfk_2');
        $this->addSql('DROP TABLE appartient');
        $this->addSql('DROP TABLE definie');
        $this->addSql('DROP TABLE appartient_produit');
        $this->addSql('DROP TABLE genere_livraison');
        $this->addSql('DROP TABLE communique');
        $this->addSql('DROP TABLE possede');
        $this->addSql('DROP TABLE observe');
        $this->addSql('ALTER TABLE adresse MODIFY Id_adresse INT NOT NULL');
        $this->addSql('DROP INDEX `primary` ON adresse');
        $this->addSql('ALTER TABLE adresse CHANGE adresse_libelle adresse_libelle VARCHAR(255) NOT NULL, CHANGE adresse_ville adresse_ville VARCHAR(255) NOT NULL, CHANGE adresse_postal adresse_postal SMALLINT NOT NULL, CHANGE adresse_type adresse_type VARCHAR(255) NOT NULL, CHANGE adresse_telephone adresse_telephone VARCHAR(255) NOT NULL, CHANGE Id_adresse id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE adresse ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE beneficie DROP FOREIGN KEY beneficie_ibfk_2');
        $this->addSql('ALTER TABLE beneficie DROP FOREIGN KEY beneficie_ibfk_1');
        $this->addSql('DROP INDEX Id_adresse ON beneficie');
        $this->addSql('DROP INDEX IDX_1C0DB026E3E87F1D ON beneficie');
        $this->addSql('ALTER TABLE beneficie ADD id INT AUTO_INCREMENT NOT NULL, DROP Id_fournisseur, DROP Id_adresse, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE commande MODIFY Id_commande INT NOT NULL');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY commande_ibfk_1');
        $this->addSql('DROP INDEX Id_client ON commande');
        $this->addSql('DROP INDEX `primary` ON commande');
        $this->addSql('ALTER TABLE commande ADD facture_id INT NOT NULL, CHANGE commande_paiement commande_paiement VARCHAR(255) NOT NULL, CHANGE commande_date commande_date DATETIME NOT NULL, CHANGE commande_date_paiement commande_date_paiement DATETIME NOT NULL, CHANGE commande_differe commande_differe TINYINT(1) NOT NULL, CHANGE commande_statut commande_statut VARCHAR(255) NOT NULL, CHANGE commande_reference commande_reference VARCHAR(255) NOT NULL, CHANGE commande_facture_date commande_facture_date DATETIME NOT NULL, CHANGE commande_total_ht commande_total_ht NUMERIC(10, 10) NOT NULL, CHANGE Id_commande id INT AUTO_INCREMENT NOT NULL, CHANGE Id_client livraison_id INT NOT NULL');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D8E54FB25 FOREIGN KEY (livraison_id) REFERENCES livraison (id)');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT FK_6EEAA67D7F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67D8E54FB25 ON commande (livraison_id)');
        $this->addSql('CREATE INDEX IDX_6EEAA67D7F2DEE08 ON commande (facture_id)');
        $this->addSql('ALTER TABLE commande ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE commande_produit ADD CONSTRAINT FK_DF1E9E8782EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE commande_produit ADD CONSTRAINT FK_DF1E9E87F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE facture MODIFY Id_facture INT NOT NULL');
        $this->addSql('ALTER TABLE facture DROP FOREIGN KEY facture_ibfk_1');
        $this->addSql('DROP INDEX Id_commande ON facture');
        $this->addSql('DROP INDEX `primary` ON facture');
        $this->addSql('ALTER TABLE facture DROP Id_commande, CHANGE facture_libelle facture_libelle VARCHAR(255) NOT NULL, CHANGE Id_facture id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE facture ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE fournisseur MODIFY Id_fournisseur INT NOT NULL');
        $this->addSql('DROP INDEX `primary` ON fournisseur');
        $this->addSql('ALTER TABLE fournisseur ADD produit_id INT NOT NULL, CHANGE fournisseur_siret fournisseur_siret VARCHAR(255) NOT NULL, CHANGE fournisseur_nom fournisseur_nom VARCHAR(255) NOT NULL, CHANGE fournisseur_telephone fournisseur_telephone VARCHAR(255) NOT NULL, CHANGE fournisseur_mail fournisseur_mail VARCHAR(255) NOT NULL, CHANGE fournisseur_constructeur fournisseur_constructeur TINYINT(1) NOT NULL, CHANGE Id_fournisseur id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE fournisseur ADD CONSTRAINT FK_369ECA32F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id)');
        $this->addSql('CREATE INDEX IDX_369ECA32F347EFB ON fournisseur (produit_id)');
        $this->addSql('ALTER TABLE fournisseur ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE fournisseur_adresse ADD CONSTRAINT FK_119F47BB670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fournisseur_adresse ADD CONSTRAINT FK_119F47BB4DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE genere DROP FOREIGN KEY genere_ibfk_1');
        $this->addSql('ALTER TABLE genere DROP FOREIGN KEY genere_ibfk_2');
        $this->addSql('DROP INDEX Id_livraison ON genere');
        $this->addSql('DROP INDEX IDX_40D56124B8654687 ON genere');
        $this->addSql('ALTER TABLE genere ADD id INT AUTO_INCREMENT NOT NULL, DROP Id_produit, DROP Id_livraison, DROP quantite, DROP PRIMARY KEY, ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE livraison MODIFY Id_livraison INT NOT NULL');
        $this->addSql('ALTER TABLE livraison DROP FOREIGN KEY livraison_ibfk_1');
        $this->addSql('DROP INDEX Id_commande ON livraison');
        $this->addSql('DROP INDEX `primary` ON livraison');
        $this->addSql('ALTER TABLE livraison DROP Id_commande, CHANGE livraison_statut livraison_statut VARCHAR(255) NOT NULL, CHANGE livraison_date livraison_date DATETIME NOT NULL, CHANGE livraison_reference livraison_reference VARCHAR(255) NOT NULL, CHANGE Id_livraison id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE livraison ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE livraison_produit ADD CONSTRAINT FK_695382458E54FB25 FOREIGN KEY (livraison_id) REFERENCES livraison (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE livraison_produit ADD CONSTRAINT FK_69538245F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE produit MODIFY Id_produit INT NOT NULL');
        $this->addSql('ALTER TABLE produit DROP FOREIGN KEY produit_ibfk_2');
        $this->addSql('ALTER TABLE produit DROP FOREIGN KEY produit_ibfk_3');
        $this->addSql('ALTER TABLE produit DROP FOREIGN KEY produit_ibfk_1');
        $this->addSql('DROP INDEX Id_tva ON produit');
        $this->addSql('DROP INDEX Id_rubrique ON produit');
        $this->addSql('DROP INDEX Id_fournisseur ON produit');
        $this->addSql('DROP INDEX `primary` ON produit');
        $this->addSql('ALTER TABLE produit ADD tva_id INT NOT NULL, ADD produit_prix_ht NUMERIC(15, 2) NOT NULL, DROP produit_price_ht, DROP Id_tva, DROP Id_rubrique, DROP Id_fournisseur, CHANGE produit_libelle produit_libelle VARCHAR(255) NOT NULL, CHANGE produit_description produit_description LONGTEXT NOT NULL, CHANGE produit_reference produit_reference VARCHAR(255) NOT NULL, CHANGE produit_image produit_image VARCHAR(255) NOT NULL, CHANGE produit_actif produit_actif TINYINT(1) NOT NULL, CHANGE produit_stock produit_stock VARCHAR(255) NOT NULL, CHANGE Id_produit id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC274D79775F FOREIGN KEY (tva_id) REFERENCES tva (id)');
        $this->addSql('CREATE INDEX IDX_29A5EC274D79775F ON produit (tva_id)');
        $this->addSql('ALTER TABLE produit ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE role MODIFY Id_role INT NOT NULL');
        $this->addSql('DROP INDEX `primary` ON role');
        $this->addSql('ALTER TABLE role CHANGE role_type role_type VARCHAR(255) NOT NULL, CHANGE role_niveau role_niveau VARCHAR(255) NOT NULL, CHANGE Id_role id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE role ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE rubrique MODIFY Id_rubrique INT NOT NULL');
        $this->addSql('ALTER TABLE rubrique DROP FOREIGN KEY rubrique_ibfk_1');
        $this->addSql('DROP INDEX Id_rubrique_id_parent ON rubrique');
        $this->addSql('DROP INDEX `primary` ON rubrique');
        $this->addSql('ALTER TABLE rubrique ADD rubrique_id INT DEFAULT NULL, CHANGE rubrique_libelle rubrique_libelle VARCHAR(255) NOT NULL, CHANGE rubrique_image rubrique_image VARCHAR(255) NOT NULL, CHANGE rubrique_description rubrique_description VARCHAR(255) NOT NULL, CHANGE Id_rubrique id INT AUTO_INCREMENT NOT NULL, CHANGE Id_rubrique_id_parent produit_id INT NOT NULL');
        $this->addSql('ALTER TABLE rubrique ADD CONSTRAINT FK_8FA4097C3BD38833 FOREIGN KEY (rubrique_id) REFERENCES rubrique (id)');
        $this->addSql('ALTER TABLE rubrique ADD CONSTRAINT FK_8FA4097CF347EFB FOREIGN KEY (produit_id) REFERENCES produit (id)');
        $this->addSql('CREATE INDEX IDX_8FA4097C3BD38833 ON rubrique (rubrique_id)');
        $this->addSql('CREATE INDEX IDX_8FA4097CF347EFB ON rubrique (produit_id)');
        $this->addSql('ALTER TABLE rubrique ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE tva MODIFY Id_tva INT NOT NULL');
        $this->addSql('DROP INDEX `primary` ON tva');
        $this->addSql('ALTER TABLE tva CHANGE tva_taux tva_taux NUMERIC(10, 2) NOT NULL, CHANGE Id_tva id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE tva ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE utilisateur MODIFY Id_client INT NOT NULL');
        $this->addSql('DROP INDEX `primary` ON utilisateur');
        $this->addSql('ALTER TABLE utilisateur ADD commande_id INT DEFAULT NULL, CHANGE utilisateur_prenom utilisateur_prenom VARCHAR(255) NOT NULL, CHANGE utilisateur_nom utilisateur_nom VARCHAR(255) NOT NULL, CHANGE utilisateur_mail utilisateur_mail VARCHAR(255) NOT NULL, CHANGE utilisateur_reference utilisateur_reference VARCHAR(255) NOT NULL, CHANGE utilisateur_mdp utilisateur_mdp VARCHAR(255) NOT NULL, CHANGE utilisateur_telephone utilisateur_telephone VARCHAR(255) NOT NULL, CHANGE utilisateur_verifie utilisateur_verifie TINYINT(1) NOT NULL, CHANGE utilisateur_coef utilisateur_coef VARCHAR(255) NOT NULL, CHANGE Id_client id INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B382EA2E54 FOREIGN KEY (commande_id) REFERENCES commande (id)');
        $this->addSql('CREATE INDEX IDX_1D1C63B382EA2E54 ON utilisateur (commande_id)');
        $this->addSql('ALTER TABLE utilisateur ADD PRIMARY KEY (id)');
        $this->addSql('ALTER TABLE utilisateur_fournisseur ADD CONSTRAINT FK_C278C7A1FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_fournisseur ADD CONSTRAINT FK_C278C7A1670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_adresse ADD CONSTRAINT FK_B954FF84FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_adresse ADD CONSTRAINT FK_B954FF844DE7DC5C FOREIGN KEY (adresse_id) REFERENCES adresse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_role ADD CONSTRAINT FK_9EE8E650FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_role ADD CONSTRAINT FK_9EE8E650D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_produit ADD CONSTRAINT FK_53AE1BB5FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE utilisateur_produit ADD CONSTRAINT FK_53AE1BB5F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE appartient (Id_commande INT NOT NULL, Id_produit INT NOT NULL, quantite NUMERIC(15, 2) DEFAULT NULL, prix_de_vente NUMERIC(19, 4) DEFAULT NULL, INDEX Id_produit (Id_produit), INDEX IDX_4201BAA7B8ADC53F (Id_commande), PRIMARY KEY(Id_commande, Id_produit)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE definie (Id_client INT NOT NULL, Id_role INT NOT NULL, INDEX Id_role (Id_role), INDEX IDX_215EB0166382331B (Id_client), PRIMARY KEY(Id_client, Id_role)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE appartient_produit (appartient_id INT NOT NULL, produit_id INT NOT NULL, INDEX IDX_900F2BADD35BF833 (appartient_id), INDEX IDX_900F2BADF347EFB (produit_id), PRIMARY KEY(appartient_id, produit_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE genere_livraison (genere_id INT NOT NULL, livraison_id INT NOT NULL, INDEX IDX_ECC8054E8E54FB25 (livraison_id), INDEX IDX_ECC8054ED35A57F1 (genere_id), PRIMARY KEY(genere_id, livraison_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE communique (Id_client INT NOT NULL, Id_fournisseur INT NOT NULL, INDEX Id_fournisseur (Id_fournisseur), INDEX IDX_FA6FF6EB6382331B (Id_client), PRIMARY KEY(Id_client, Id_fournisseur)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE possede (Id_client INT NOT NULL, Id_adresse INT NOT NULL, INDEX Id_adresse (Id_adresse), INDEX IDX_3D0B15086382331B (Id_client), PRIMARY KEY(Id_client, Id_adresse)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE observe (Id_produit INT NOT NULL, Id_client INT NOT NULL, INDEX Id_client (Id_client), INDEX IDX_4EC2794B8654687 (Id_produit), PRIMARY KEY(Id_produit, Id_client)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE appartient ADD CONSTRAINT appartient_ibfk_1 FOREIGN KEY (Id_commande) REFERENCES commande (Id_commande)');
        $this->addSql('ALTER TABLE appartient ADD CONSTRAINT appartient_ibfk_2 FOREIGN KEY (Id_produit) REFERENCES produit (Id_produit)');
        $this->addSql('ALTER TABLE definie ADD CONSTRAINT definie_ibfk_2 FOREIGN KEY (Id_role) REFERENCES role (Id_role)');
        $this->addSql('ALTER TABLE definie ADD CONSTRAINT definie_ibfk_1 FOREIGN KEY (Id_client) REFERENCES utilisateur (Id_client)');
        $this->addSql('ALTER TABLE communique ADD CONSTRAINT communique_ibfk_1 FOREIGN KEY (Id_client) REFERENCES utilisateur (Id_client)');
        $this->addSql('ALTER TABLE communique ADD CONSTRAINT communique_ibfk_2 FOREIGN KEY (Id_fournisseur) REFERENCES fournisseur (Id_fournisseur)');
        $this->addSql('ALTER TABLE possede ADD CONSTRAINT possede_ibfk_2 FOREIGN KEY (Id_adresse) REFERENCES adresse (Id_adresse)');
        $this->addSql('ALTER TABLE possede ADD CONSTRAINT possede_ibfk_1 FOREIGN KEY (Id_client) REFERENCES utilisateur (Id_client)');
        $this->addSql('ALTER TABLE observe ADD CONSTRAINT observe_ibfk_1 FOREIGN KEY (Id_produit) REFERENCES produit (Id_produit)');
        $this->addSql('ALTER TABLE observe ADD CONSTRAINT observe_ibfk_2 FOREIGN KEY (Id_client) REFERENCES utilisateur (Id_client)');
        $this->addSql('ALTER TABLE detail_commande DROP FOREIGN KEY FK_98344FA682EA2E54');
        $this->addSql('ALTER TABLE detail_commande DROP FOREIGN KEY FK_98344FA6AABEFE2C');
        $this->addSql('ALTER TABLE detail_commande DROP FOREIGN KEY FK_98344FA69AF8E3A3');
        $this->addSql('ALTER TABLE detail_livraison DROP FOREIGN KEY FK_B7FB4AAAAD958E57');
        $this->addSql('ALTER TABLE detail_livraison DROP FOREIGN KEY FK_B7FB4AAAAABEFE2C');
        $this->addSql('DROP TABLE detail_commande');
        $this->addSql('DROP TABLE detail_livraison');
        $this->addSql('ALTER TABLE commande_produit DROP FOREIGN KEY FK_DF1E9E8782EA2E54');
        $this->addSql('ALTER TABLE commande_produit DROP FOREIGN KEY FK_DF1E9E87F347EFB');
        $this->addSql('ALTER TABLE utilisateur_role DROP FOREIGN KEY FK_9EE8E650FB88E14F');
        $this->addSql('ALTER TABLE utilisateur_role DROP FOREIGN KEY FK_9EE8E650D60322AC');
        $this->addSql('ALTER TABLE produit MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE produit DROP FOREIGN KEY FK_29A5EC274D79775F');
        $this->addSql('DROP INDEX IDX_29A5EC274D79775F ON produit');
        $this->addSql('DROP INDEX `PRIMARY` ON produit');
        $this->addSql('ALTER TABLE produit ADD produit_price_ht NUMERIC(15, 2) DEFAULT NULL, ADD Id_rubrique INT NOT NULL, ADD Id_fournisseur INT NOT NULL, DROP produit_prix_ht, CHANGE produit_libelle produit_libelle VARCHAR(255) DEFAULT NULL, CHANGE produit_description produit_description TEXT DEFAULT NULL, CHANGE produit_reference produit_reference VARCHAR(255) DEFAULT NULL, CHANGE produit_image produit_image VARCHAR(255) DEFAULT NULL, CHANGE produit_actif produit_actif TINYINT(1) DEFAULT NULL, CHANGE produit_stock produit_stock VARCHAR(255) DEFAULT NULL, CHANGE id Id_produit INT AUTO_INCREMENT NOT NULL, CHANGE tva_id Id_tva INT NOT NULL');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT produit_ibfk_2 FOREIGN KEY (Id_rubrique) REFERENCES rubrique (Id_rubrique)');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT produit_ibfk_3 FOREIGN KEY (Id_fournisseur) REFERENCES fournisseur (Id_fournisseur)');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT produit_ibfk_1 FOREIGN KEY (Id_tva) REFERENCES tva (Id_tva)');
        $this->addSql('CREATE INDEX Id_tva ON produit (Id_tva)');
        $this->addSql('CREATE INDEX Id_rubrique ON produit (Id_rubrique)');
        $this->addSql('CREATE INDEX Id_fournisseur ON produit (Id_fournisseur)');
        $this->addSql('ALTER TABLE produit ADD PRIMARY KEY (Id_produit)');
        $this->addSql('ALTER TABLE tva MODIFY id INT NOT NULL');
        $this->addSql('DROP INDEX `PRIMARY` ON tva');
        $this->addSql('ALTER TABLE tva CHANGE tva_taux tva_taux NUMERIC(15, 2) DEFAULT NULL, CHANGE id Id_tva INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE tva ADD PRIMARY KEY (Id_tva)');
        $this->addSql('ALTER TABLE facture MODIFY id INT NOT NULL');
        $this->addSql('DROP INDEX `PRIMARY` ON facture');
        $this->addSql('ALTER TABLE facture ADD Id_commande INT NOT NULL, CHANGE facture_libelle facture_libelle VARCHAR(255) DEFAULT NULL, CHANGE id Id_facture INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT facture_ibfk_1 FOREIGN KEY (Id_commande) REFERENCES commande (Id_commande)');
        $this->addSql('CREATE INDEX Id_commande ON facture (Id_commande)');
        $this->addSql('ALTER TABLE facture ADD PRIMARY KEY (Id_facture)');
        $this->addSql('ALTER TABLE commande MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY FK_6EEAA67D8E54FB25');
        $this->addSql('ALTER TABLE commande DROP FOREIGN KEY FK_6EEAA67D7F2DEE08');
        $this->addSql('DROP INDEX IDX_6EEAA67D8E54FB25 ON commande');
        $this->addSql('DROP INDEX IDX_6EEAA67D7F2DEE08 ON commande');
        $this->addSql('DROP INDEX `PRIMARY` ON commande');
        $this->addSql('ALTER TABLE commande ADD Id_client INT NOT NULL, DROP livraison_id, DROP facture_id, CHANGE commande_paiement commande_paiement VARCHAR(255) DEFAULT NULL, CHANGE commande_date commande_date DATETIME DEFAULT NULL, CHANGE commande_date_paiement commande_date_paiement DATETIME DEFAULT NULL, CHANGE commande_differe commande_differe TINYINT(1) DEFAULT NULL, CHANGE commande_statut commande_statut VARCHAR(255) DEFAULT NULL, CHANGE commande_reference commande_reference VARCHAR(255) DEFAULT NULL, CHANGE commande_facture_date commande_facture_date DATETIME DEFAULT NULL, CHANGE commande_total_ht commande_total_ht NUMERIC(15, 2) DEFAULT NULL, CHANGE id Id_commande INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE commande ADD CONSTRAINT commande_ibfk_1 FOREIGN KEY (Id_client) REFERENCES utilisateur (Id_client)');
        $this->addSql('CREATE INDEX Id_client ON commande (Id_client)');
        $this->addSql('ALTER TABLE commande ADD PRIMARY KEY (Id_commande)');
        $this->addSql('ALTER TABLE livraison_produit DROP FOREIGN KEY FK_695382458E54FB25');
        $this->addSql('ALTER TABLE livraison_produit DROP FOREIGN KEY FK_69538245F347EFB');
        $this->addSql('ALTER TABLE rubrique MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE rubrique DROP FOREIGN KEY FK_8FA4097C3BD38833');
        $this->addSql('ALTER TABLE rubrique DROP FOREIGN KEY FK_8FA4097CF347EFB');
        $this->addSql('DROP INDEX IDX_8FA4097C3BD38833 ON rubrique');
        $this->addSql('DROP INDEX IDX_8FA4097CF347EFB ON rubrique');
        $this->addSql('DROP INDEX `PRIMARY` ON rubrique');
        $this->addSql('ALTER TABLE rubrique DROP rubrique_id, CHANGE rubrique_libelle rubrique_libelle VARCHAR(255) DEFAULT NULL, CHANGE rubrique_image rubrique_image VARCHAR(255) DEFAULT NULL, CHANGE rubrique_description rubrique_description VARCHAR(255) DEFAULT NULL, CHANGE id Id_rubrique INT AUTO_INCREMENT NOT NULL, CHANGE produit_id Id_rubrique_id_parent INT NOT NULL');
        $this->addSql('ALTER TABLE rubrique ADD CONSTRAINT rubrique_ibfk_1 FOREIGN KEY (Id_rubrique_id_parent) REFERENCES rubrique (Id_rubrique)');
        $this->addSql('CREATE INDEX Id_rubrique_id_parent ON rubrique (Id_rubrique_id_parent)');
        $this->addSql('ALTER TABLE rubrique ADD PRIMARY KEY (Id_rubrique)');
        $this->addSql('ALTER TABLE adresse MODIFY id INT NOT NULL');
        $this->addSql('DROP INDEX `PRIMARY` ON adresse');
        $this->addSql('ALTER TABLE adresse CHANGE adresse_libelle adresse_libelle VARCHAR(255) DEFAULT NULL, CHANGE adresse_ville adresse_ville VARCHAR(255) DEFAULT NULL, CHANGE adresse_postal adresse_postal TINYINT(1) DEFAULT NULL, CHANGE adresse_type adresse_type VARCHAR(255) DEFAULT NULL, CHANGE adresse_telephone adresse_telephone VARCHAR(255) DEFAULT NULL, CHANGE id Id_adresse INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE adresse ADD PRIMARY KEY (Id_adresse)');
        $this->addSql('ALTER TABLE genere MODIFY id INT NOT NULL');
        $this->addSql('DROP INDEX `PRIMARY` ON genere');
        $this->addSql('ALTER TABLE genere ADD Id_produit INT NOT NULL, ADD Id_livraison INT NOT NULL, ADD quantite INT DEFAULT NULL, DROP id');
        $this->addSql('ALTER TABLE genere ADD CONSTRAINT genere_ibfk_1 FOREIGN KEY (Id_produit) REFERENCES produit (Id_produit)');
        $this->addSql('ALTER TABLE genere ADD CONSTRAINT genere_ibfk_2 FOREIGN KEY (Id_livraison) REFERENCES livraison (Id_livraison)');
        $this->addSql('CREATE INDEX Id_livraison ON genere (Id_livraison)');
        $this->addSql('CREATE INDEX IDX_40D56124B8654687 ON genere (Id_produit)');
        $this->addSql('ALTER TABLE genere ADD PRIMARY KEY (Id_produit, Id_livraison)');
        $this->addSql('ALTER TABLE utilisateur MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE utilisateur DROP FOREIGN KEY FK_1D1C63B382EA2E54');
        $this->addSql('DROP INDEX IDX_1D1C63B382EA2E54 ON utilisateur');
        $this->addSql('DROP INDEX `PRIMARY` ON utilisateur');
        $this->addSql('ALTER TABLE utilisateur DROP commande_id, CHANGE utilisateur_prenom utilisateur_prenom VARCHAR(255) DEFAULT NULL, CHANGE utilisateur_nom utilisateur_nom VARCHAR(255) DEFAULT NULL, CHANGE utilisateur_mail utilisateur_mail VARCHAR(255) DEFAULT NULL, CHANGE utilisateur_reference utilisateur_reference VARCHAR(255) DEFAULT NULL, CHANGE utilisateur_mdp utilisateur_mdp VARCHAR(255) DEFAULT NULL, CHANGE utilisateur_telephone utilisateur_telephone VARCHAR(255) DEFAULT NULL, CHANGE utilisateur_verifie utilisateur_verifie TINYINT(1) DEFAULT NULL, CHANGE utilisateur_coef utilisateur_coef VARCHAR(255) DEFAULT NULL, CHANGE id Id_client INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE utilisateur ADD PRIMARY KEY (Id_client)');
        $this->addSql('ALTER TABLE beneficie MODIFY id INT NOT NULL');
        $this->addSql('DROP INDEX `PRIMARY` ON beneficie');
        $this->addSql('ALTER TABLE beneficie ADD Id_fournisseur INT NOT NULL, ADD Id_adresse INT NOT NULL, DROP id');
        $this->addSql('ALTER TABLE beneficie ADD CONSTRAINT beneficie_ibfk_2 FOREIGN KEY (Id_adresse) REFERENCES adresse (Id_adresse)');
        $this->addSql('ALTER TABLE beneficie ADD CONSTRAINT beneficie_ibfk_1 FOREIGN KEY (Id_fournisseur) REFERENCES fournisseur (Id_fournisseur)');
        $this->addSql('CREATE INDEX Id_adresse ON beneficie (Id_adresse)');
        $this->addSql('CREATE INDEX IDX_1C0DB026E3E87F1D ON beneficie (Id_fournisseur)');
        $this->addSql('ALTER TABLE beneficie ADD PRIMARY KEY (Id_fournisseur, Id_adresse)');
        $this->addSql('ALTER TABLE role MODIFY id INT NOT NULL');
        $this->addSql('DROP INDEX `PRIMARY` ON role');
        $this->addSql('ALTER TABLE role CHANGE role_type role_type VARCHAR(255) DEFAULT NULL, CHANGE role_niveau role_niveau VARCHAR(255) DEFAULT NULL, CHANGE id Id_role INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE role ADD PRIMARY KEY (Id_role)');
        $this->addSql('ALTER TABLE utilisateur_produit DROP FOREIGN KEY FK_53AE1BB5FB88E14F');
        $this->addSql('ALTER TABLE utilisateur_produit DROP FOREIGN KEY FK_53AE1BB5F347EFB');
        $this->addSql('ALTER TABLE fournisseur_adresse DROP FOREIGN KEY FK_119F47BB670C757F');
        $this->addSql('ALTER TABLE fournisseur_adresse DROP FOREIGN KEY FK_119F47BB4DE7DC5C');
        $this->addSql('ALTER TABLE livraison MODIFY id INT NOT NULL');
        $this->addSql('DROP INDEX `PRIMARY` ON livraison');
        $this->addSql('ALTER TABLE livraison ADD Id_commande INT NOT NULL, CHANGE livraison_statut livraison_statut VARCHAR(255) DEFAULT NULL, CHANGE livraison_date livraison_date DATETIME DEFAULT NULL, CHANGE livraison_reference livraison_reference VARCHAR(255) DEFAULT NULL, CHANGE id Id_livraison INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE livraison ADD CONSTRAINT livraison_ibfk_1 FOREIGN KEY (Id_commande) REFERENCES commande (Id_commande)');
        $this->addSql('CREATE INDEX Id_commande ON livraison (Id_commande)');
        $this->addSql('ALTER TABLE livraison ADD PRIMARY KEY (Id_livraison)');
        $this->addSql('ALTER TABLE utilisateur_adresse DROP FOREIGN KEY FK_B954FF84FB88E14F');
        $this->addSql('ALTER TABLE utilisateur_adresse DROP FOREIGN KEY FK_B954FF844DE7DC5C');
        $this->addSql('ALTER TABLE utilisateur_fournisseur DROP FOREIGN KEY FK_C278C7A1FB88E14F');
        $this->addSql('ALTER TABLE utilisateur_fournisseur DROP FOREIGN KEY FK_C278C7A1670C757F');
        $this->addSql('ALTER TABLE fournisseur MODIFY id INT NOT NULL');
        $this->addSql('ALTER TABLE fournisseur DROP FOREIGN KEY FK_369ECA32F347EFB');
        $this->addSql('DROP INDEX IDX_369ECA32F347EFB ON fournisseur');
        $this->addSql('DROP INDEX `PRIMARY` ON fournisseur');
        $this->addSql('ALTER TABLE fournisseur DROP produit_id, CHANGE fournisseur_siret fournisseur_siret VARCHAR(255) DEFAULT NULL, CHANGE fournisseur_nom fournisseur_nom VARCHAR(255) DEFAULT NULL, CHANGE fournisseur_telephone fournisseur_telephone VARCHAR(255) DEFAULT NULL, CHANGE fournisseur_mail fournisseur_mail VARCHAR(255) DEFAULT NULL, CHANGE fournisseur_constructeur fournisseur_constructeur TINYINT(1) DEFAULT NULL, CHANGE id Id_fournisseur INT AUTO_INCREMENT NOT NULL');
        $this->addSql('ALTER TABLE fournisseur ADD PRIMARY KEY (Id_fournisseur)');
    }
}
